# Assignment 1




### Import numpy as np

In [4]:
import numpy as np


### Make a python matrix (3 * 3)=>[[1,2,3],[4,5,6],[7,8,9]]convert it into numpy array and print it

In [7]:
matrix1=[[1,2,3],[4,5,6],[7,8,9]]
matrix1
np.array(matrix1)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Make a matrix  (3 * 3) using built in methods(like arange(),reshape() etc) 

In [16]:
np.arange(1,18,2).reshape(3,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

### Create a numpy array with 10 random numbers from 0 to 10( there should be few numbers greater than 1)

In [99]:

np.random.randint(0,10,10)



array([2, 5, 9, 6, 9, 6, 1, 2, 9, 8])

### create a numpy array=>[1,2,3,4,5] & convert it into 2D arrays with 5 rows

In [119]:
arr=np.array([1,2,3,4,5,1,2,3,4,5])
print(arr)

arr2=np.reshape(arr,(5,2))
print(arr2)

[1 2 3 4 5 1 2 3 4 5]
[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


### Print the shape of above created array 

In [114]:
print (arr2.shape)

(5, 2)


### create a numpy array with 10 elements in it,Access & print its 3rd,4th and 9th element

In [130]:
arr=arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr[3])
print(arr[4])
print(arr[9])

4
5
10


###  print alternate elements of that array

In [142]:
arr=np.arange(2,11,2)
arr

array([ 2,  4,  6,  8, 10])

### change last 3 elements into 100 using broadcasting and print

In [143]:
arr[2:5]=100
arr

array([  2,   4, 100, 100, 100])

### create 5 * 5 matrix (fill it with any element you like).print it .Then the middle (3*3) matrix

In [146]:
matrix2 =np.arange(1,26)
matrix2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [147]:
matrix2.reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [148]:
matrixsub=matrix2.reshape(5,5)[1:4,1:4]
matrixsub

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])